openers:
  - type: text
    tools:
      - name: "Main Editor"
        cmd: "nvim"
      - name: "Main Editor (Sudo)"
        cmd: "sudo nvim"
      - name: "Pager"
        cmd: "less"
      - name: "vim"
        cmd: "vim"
      - name: "vi"
        cmd: "vi"
    mime_types:
      - "text/plain"
      - "text/*"
      - "application/javascript"
      - "application/ecmascript"
      - "application/x-ecmascript"
      - "application/x-javascript"
      - "text/ecmascript"
      - "text/javascript1.0"
      - "text/javascript1.1"
      - "text/javascript1.2"
      - "text/javascript1.3"
      - "text/javascript1.4"
      - "text/javascript1.5"
      - "text/jscript"
      - "text/livescript"
      - "text/x-ecmascript"
      - "text/x-javascript"
      - "text/markdown"
      - "application/json"
      - "text/x-shellscript"
      - "text/css"
      - "text/x-python"
      - "application/x-sh"
      - "text/html"
      - "inode/x-empty"
      - "text/x-php"
      - "application/x-mspublisher"
  - type: spreadsheet
    tools:
      - name: LibreOffice
        cmd: libreoffice
    mime_types:
      - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
      - "application/vnd.oasis.opendocument.spreadsheet"
  - type: pdf
    tools:
      - name: Zathura
        cmd: zathura
    mime_types:
      - "image/vnd.djvu"
      - "application/pdf"
      - "application/octet-stream"
      - "application/postscript"
  - type: audio
    tools:
    mime_types:
      - "audio/x-aiff"
      - "audio/mpeg"
  - type: video
    tools:
    mime_types:
      - "video/x-matroska"
      - "video/3gpp"
      - "video/x-ms-asf"
      - "video/3gpp"
      - "video/3gpp"
      - "video/x-flv"
      - "video/mpeg"
      - "video/x-msvideo"
      - "video/x-f4v"
      - "video/x-m4v"
      - "video/quicktime"
      - "video/mp4"
      - "model/vnd.mts"
      - "application/mxf"
      - "video/ogg"
      - "application/vnd.rn-realmedia"
      - "application/x-shockwave-flash"
      - "text/vnd.trolltech.linguist"
      - "video/x-ms-vob"
      - "video/webm"
      - "video/x-ms-wmv"
  - type: image
    tools:
      - name: "View"
        cmd: "nsxiv"
      - name: "Edit"
        cmd: "pinta"
    mime_types:
      - "image/png"
      - "image/jpeg"
      - "image/webp"
      - "image/gif"
  - type: drawing
    mime_types:
      - application/vnd.oasis.opendocument.graphics
    tools:
      - name: LibreOffice
        cmd: libreoffice
